name: Push to Screeps server

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch'
        required: true
        default: 'default'
        type: string

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Push
      run: |
        npm install
        npm install grunt
        npm install grunt-screeps
        grunt screeps
