name: Update Cartographer

on:
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Cartographer
        uses: actions/checkout@v3
        with:
          repository: glitchassassin/screeps

      - name: Check out own repository
        uses: actions/checkout@v3
        with:
          path: "./my-repo"

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Build Cartographer
        run: |
          npm install
          npm run-script build
          cp ./src/main.js ./my-repo/screeps-cartographer.js

      - name: Prepare commit
        run: sudo chown -Rc $UID .git/

      - name: Commit and push Cartographer
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "auto-build Cartographer"
          repository: "./my-repo"
